version: "3.8"
services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api
    ports:
      - '3000:3000'
    # env_file:
    #   - .env
    environment:
      PORT: 3000
      NODE_ENV: development

    depends_on:
      - mysql
    volumes:
      - ./src:/usr/src/app/src
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    # env_file:
    #   - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ansur
      MYSQL_USER: javier
      MYSQL_PASSWORD: javier123
    ports:
      - '3307:3306'

# version: "3"

# services:
#   backend:
#     build: ./
#     container_name: nestjs_api
#     environment:
#       - PORT=3000
#       - NODE_ENV=development
#       - DB_ROOT_PASSWORD=root
#       - DB_HOST=mysql_db
#       - DB_PORT=3306
#       - DB_NAME=db_ansur
#       - DB_USER=javier
#       - DB_PASSWORD=javier123
#       - DB_SSL=false
#       - JWT_SECRET=mi_clave_de_seguridad
#     ports:
#       - '3000:3000'
#     depends_on:
#       - database
#     networks:
#       - nestjs_network

#   database:
#     image: mysql:8.0
#     container_name: mysql_db
#     ports:
#       - "3307:3306"
#     volumes:
#       - './mysqldb-backup:/data/db'
#     networks:
#       - nestjs_network

# networks:
#   nestjs_network:
#     driver: bridge
